apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-kdlc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-tcsa-tenant/appstudio/devfile-sample-python-basic-kdlc@sha256:3a8a9d8cedef177e94ecb50c623c604c4951415765d69ac3239dcdadfecdcaff
        name: my-python
        resources: {}
status: {}
