apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-whrg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-whrg
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-whrg
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-whrg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-whrg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-tcsa-tenant/appstudio/dc-metro-map-whrg@sha256:eafbbe1793760038f10717ee46dda2fab17274835c3f0e77ab153c2e1876cb6d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
